{% set name = "pilot1-tools" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name }}"
  version: {{ data.get('version') }}

source:
  path: .
  # Disabled due to https://github.com/conda/conda-build/issues/1462
  # git_url: https://github.com/globusonline/{{ name }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - tableschema
  run:
    - globus-sdk
    - fair-research-login
    - python
    - pytz
    - jsonschema
    - pandas
    - click
    - tableschema
    - configobj
    - python-slugify
    - requests-toolbelt

test:
  imports:
    - pilot
    - tests

about:
  home: https://github.com/globusonline/{{ name }}
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: A generalized library for storing native auth tokens
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - NickolausDS
